[package]
name = "farenheit_to_celcius_rust"
version = "0.1.0"
authors = ["Samuel Santiago <ssantiago1@carthage.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
